#!/bin/bash
declare -A zonemap

zonemap["ap-east-1"]="ape1"
zonemap["ap-east-1a"]="ape1a"
zonemap["ap-east-1b"]="ape1b"
zonemap["ap-east-1c"]="ape1c"
zonemap["ap-east-1d"]="ape1d"
zonemap["ap-east-1e"]="ape1e"
zonemap["ap-east-1f"]="ape1f"
zonemap["ap-east-1g"]="ape1g"
zonemap["ap-east-1h"]="ape1h"

zonemap["ap-northeast-1"]="apne1"
zonemap["ap-northeast-1a"]="apne1a"
zonemap["ap-northeast-1b"]="apne1b"
zonemap["ap-northeast-1c"]="apne1c"
zonemap["ap-northeast-1d"]="apne1d"
zonemap["ap-northeast-1e"]="apne1e"
zonemap["ap-northeast-1f"]="apne1f"
zonemap["ap-northeast-1g"]="apne1g"
zonemap["ap-northeast-1h"]="apne1h"

zonemap["ap-northeast-2"]="apne2"
zonemap["ap-northeast-2a"]="apne2a"
zonemap["ap-northeast-2b"]="apne2b"
zonemap["ap-northeast-2c"]="apne2c"
zonemap["ap-northeast-2d"]="apne2d"
zonemap["ap-northeast-2e"]="apne2e"
zonemap["ap-northeast-2f"]="apne2f"
zonemap["ap-northeast-2g"]="apne2g"
zonemap["ap-northeast-2h"]="apne2h"

zonemap["ap-south-1"]="aps1"
zonemap["ap-south-1a"]="aps1a"
zonemap["ap-south-1b"]="aps1b"
zonemap["ap-south-1c"]="aps1c"
zonemap["ap-south-1d"]="aps1d"
zonemap["ap-south-1e"]="aps1e"
zonemap["ap-south-1f"]="aps1f"
zonemap["ap-south-1g"]="aps1g"
zonemap["ap-south-1h"]="aps1h"

zonemap["ap-southeast-1"]="apse1"
zonemap["ap-southeast-1a"]="apse1a"
zonemap["ap-southeast-1b"]="apse1b"
zonemap["ap-southeast-1c"]="apse1c"
zonemap["ap-southeast-1d"]="apse1d"
zonemap["ap-southeast-1e"]="apse1e"
zonemap["ap-southeast-1f"]="apse1f"
zonemap["ap-southeast-1g"]="apse1g"
zonemap["ap-southeast-1h"]="apse1h"

zonemap["ap-southeast-2"]="apse2"
zonemap["ap-southeast-2a"]="apse2a"
zonemap["ap-southeast-2b"]="apse2b"
zonemap["ap-southeast-2c"]="apse2c"
zonemap["ap-southeast-2d"]="apse2d"
zonemap["ap-southeast-2e"]="apse2e"
zonemap["ap-southeast-2f"]="apse2f"
zonemap["ap-southeast-2g"]="apse2g"
zonemap["ap-southeast-2h"]="apse2h"

zonemap["ca-central-1"]="cac1"
zonemap["ca-central-1a"]="cac1a"
zonemap["ca-central-1b"]="cac1b"
zonemap["ca-central-1c"]="cac1c"
zonemap["ca-central-1d"]="cac1d"
zonemap["ca-central-1e"]="cac1e"
zonemap["ca-central-1f"]="cac1f"
zonemap["ca-central-1g"]="cac1g"
zonemap["ca-central-1h"]="cac1h"

zonemap["eu-central-1"]="euc1"
zonemap["eu-central-1a"]="euc1a"
zonemap["eu-central-1b"]="euc1b"
zonemap["eu-central-1c"]="euc1c"
zonemap["eu-central-1d"]="euc1d"
zonemap["eu-central-1e"]="euc1e"
zonemap["eu-central-1f"]="euc1f"
zonemap["eu-central-1g"]="euc1g"
zonemap["eu-central-1h"]="euc1h"

zonemap["eu-north-1"]="eun1"
zonemap["eu-north-1a"]="eun1a"
zonemap["eu-north-1b"]="eun1b"
zonemap["eu-north-1c"]="eun1c"
zonemap["eu-north-1d"]="eun1d"
zonemap["eu-north-1e"]="eun1e"
zonemap["eu-north-1f"]="eun1f"
zonemap["eu-north-1g"]="eun1g"
zonemap["eu-north-1h"]="eun1h"

zonemap["eu-south-1"]="eus1"
zonemap["eu-south-1a"]="eus1a"
zonemap["eu-south-1b"]="eus1b"
zonemap["eu-south-1c"]="eus1c"
zonemap["eu-south-1d"]="eus1d"
zonemap["eu-south-1e"]="eus1e"
zonemap["eu-south-1f"]="eus1f"
zonemap["eu-south-1g"]="eus1g"
zonemap["eu-south-1h"]="eus1h"

zonemap["eu-west-1"]="euw1"
zonemap["eu-west-1a"]="euw1a"
zonemap["eu-west-1b"]="euw1b"
zonemap["eu-west-1c"]="euw1c"
zonemap["eu-west-1d"]="euw1d"
zonemap["eu-west-1e"]="euw1e"
zonemap["eu-west-1f"]="euw1f"
zonemap["eu-west-1g"]="euw1g"
zonemap["eu-west-1h"]="euw1h"

zonemap["eu-west-2"]="euw2"
zonemap["eu-west-2a"]="euw2a"
zonemap["eu-west-2b"]="euw2b"
zonemap["eu-west-2c"]="euw2c"
zonemap["eu-west-2d"]="euw2d"
zonemap["eu-west-2e"]="euw2e"
zonemap["eu-west-2f"]="euw2f"
zonemap["eu-west-2g"]="euw2g"
zonemap["eu-west-2h"]="euw2h"

zonemap["eu-west-3"]="euw3"
zonemap["eu-west-3a"]="euw3a"
zonemap["eu-west-3b"]="euw3b"
zonemap["eu-west-3c"]="euw3c"
zonemap["eu-west-3d"]="euw3d"
zonemap["eu-west-3e"]="euw3e"
zonemap["eu-west-3f"]="euw3f"
zonemap["eu-west-3g"]="euw3g"
zonemap["eu-west-3h"]="euw3h"

zonemap["af-south-1"]="afs1"
zonemap["af-south-1a"]="afs1a"
zonemap["af-south-1b"]="afs1b"
zonemap["af-south-1c"]="afs1c"
zonemap["af-south-1d"]="afs1d"
zonemap["af-south-1e"]="afs1e"
zonemap["af-south-1f"]="afs1f"
zonemap["af-south-1g"]="afs1g"
zonemap["af-south-1h"]="afs1h"

zonemap["us-gov-east-1"]="usge1"
zonemap["us-gov-east-1a"]="usge1a"
zonemap["us-gov-east-1b"]="usge1b"
zonemap["us-gov-east-1c"]="usge1c"
zonemap["us-gov-east-1d"]="usge1d"
zonemap["us-gov-east-1e"]="usge1e"
zonemap["us-gov-east-1f"]="usge1f"
zonemap["us-gov-east-1g"]="usge1g"
zonemap["us-gov-east-1h"]="usge1h"

zonemap["us-gov-west-1"]="usgw1"
zonemap["us-gov-west-1a"]="usgw1a"
zonemap["us-gov-west-1b"]="usgw1b"
zonemap["us-gov-west-1c"]="usgw1c"
zonemap["us-gov-west-1d"]="usgw1d"
zonemap["us-gov-west-1e"]="usgw1e"
zonemap["us-gov-west-1f"]="usgw1f"
zonemap["us-gov-west-1g"]="usgw1g"
zonemap["us-gov-west-1h"]="usgw1h"

zonemap["me-south-1"]="mes1"
zonemap["me-south-1a"]="mes1a"
zonemap["me-south-1b"]="mes1b"
zonemap["me-south-1c"]="mes1c"
zonemap["me-south-1d"]="mes1d"
zonemap["me-south-1e"]="mes1e"
zonemap["me-south-1f"]="mes1f"
zonemap["me-south-1g"]="mes1g"
zonemap["me-south-1h"]="mes1h"

zonemap["cn-north-1"]="cnn1"
zonemap["cn-north-1a"]="cnn1a"
zonemap["cn-north-1b"]="cnn1b"
zonemap["cn-north-1c"]="cnn1c"
zonemap["cn-north-1d"]="cnn1d"
zonemap["cn-north-1e"]="cnn1e"
zonemap["cn-north-1f"]="cnn1f"
zonemap["cn-north-1g"]="cnn1g"
zonemap["cn-north-1h"]="cnn1h"

zonemap["cn-northwest-1"]="cnnw1"
zonemap["cn-northwest-1a"]="cnnw1a"
zonemap["cn-northwest-1b"]="cnnw1b"
zonemap["cn-northwest-1c"]="cnnw1c"
zonemap["cn-northwest-1d"]="cnnw1d"
zonemap["cn-northwest-1e"]="cnnw1e"
zonemap["cn-northwest-1f"]="cnnw1f"
zonemap["cn-northwest-1g"]="cnnw1g"
zonemap["cn-northwest-1h"]="cnnw1h"

zonemap["sa-east-1"]="sae1"
zonemap["sa-east-1a"]="sae1a"
zonemap["sa-east-1b"]="sae1b"
zonemap["sa-east-1c"]="sae1c"
zonemap["sa-east-1d"]="sae1d"
zonemap["sa-east-1e"]="sae1e"
zonemap["sa-east-1f"]="sae1f"
zonemap["sa-east-1g"]="sae1g"
zonemap["sa-east-1h"]="sae1h"

zonemap["us-east-1"]="use1"
zonemap["us-east-1a"]="use1a"
zonemap["us-east-1b"]="use1b"
zonemap["us-east-1c"]="use1c"
zonemap["us-east-1d"]="use1d"
zonemap["us-east-1e"]="use1e"
zonemap["us-east-1f"]="use1f"
zonemap["us-east-1g"]="use1g"
zonemap["us-east-1h"]="use1h"

zonemap["us-east-2"]="use2"
zonemap["us-east-2a"]="use2a"
zonemap["us-east-2b"]="use2b"
zonemap["us-east-2c"]="use2c"
zonemap["us-east-2d"]="use2d"
zonemap["us-east-2e"]="use2e"
zonemap["us-east-2f"]="use2f"
zonemap["us-east-2g"]="use2g"
zonemap["us-east-2h"]="use2h"

zonemap["us-west-1"]="usw1"
zonemap["us-west-1a"]="usw1a"
zonemap["us-west-1b"]="usw1b"
zonemap["us-west-1c"]="usw1c"
zonemap["us-west-1d"]="usw1d"
zonemap["us-west-1e"]="usw1e"
zonemap["us-west-1f"]="usw1f"
zonemap["us-west-1g"]="usw1g"
zonemap["us-west-1h"]="usw1h"

zonemap["us-west-2"]="usw2"
zonemap["us-west-2a"]="usw2a"
zonemap["us-west-2b"]="usw2b"
zonemap["us-west-2c"]="usw2c"
zonemap["us-west-2d"]="usw2d"
zonemap["us-west-2e"]="usw2e"
zonemap["us-west-2f"]="usw2f"
zonemap["us-west-2g"]="usw2g"
zonemap["us-west-2h"]="usw2h"

zonemap["us-west-2-lax-1a"]="lax1a"
zonemap["us-west-2-lax-1b"]="lax1b"
zonemap["us-west-2-lax-1c"]="lax1c"
zonemap["us-west-2-lax-1d"]="lax1d"